### https://github.com/shichunlei/-Api/blob/master/%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1.md#new_movies
post http://175.178.126.10:8000/api/v1/hotmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 1,
    "city": "郑州"
}

### Swiper request /api/v1/swiperdata
get http://175.178.126.10:8000/api/v1/swiperdata

### Hot movie request /api/v1/hotmovie
### 即将上映影视
post https://api.douban.com/v2/movie/coming_soon
Content-Type:application/json

{
    "start": 0,
    "count": 1,
    "city": "郑州",
    "apikey": "0ab215a8b1977939201640fa14c66bab"
}

### 即将上映
post http://175.178.126.10:8000/api/v1/soonmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 1
}

### 最新上映
post http://175.178.126.10:8000/api/v1/newmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 1
}

### 周榜
post http://175.178.126.10:8000/api/v1/weekmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 1
}

### 北美票房榜
post http://175.178.126.10:8000/api/v1/usmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 1
}

### 电影详情
post http://175.178.126.10:8000/api/v1/detailmovie
Content-Type:application/json
 
{
    "id": "1292052"
}
### 电影短评
post http://175.178.126.10:8000/api/v1/commentmovie
Content-Type:application/json
 
{
    "id": "1292052",
    "start": 0,
    "count": 2
}
### 电影剧照
post http://175.178.126.10:8000/api/v1/photomovie
Content-Type:application/json
 
{
    "id": "1292052",
    "start": 0,
    "count": 2
}
### top250 movie request /api/v1/topmovie
post http://175.178.126.10:8000/api/v1/topmovie
Content-Type:application/json
 
{
    "start": 0,
    "count": 2
}

### 电影票房信息
get http://175.178.126.10:8000/api/v1/piaomovie



### Below is the code of douban.http,use vscode extension REST Client to send request.
###正在热映影视
post https://api.douban.com/v2/movie/in_theaters
Content-Type:application/json
 
{
    "start": 0,
    "count": 1,
    "city": "郑州",
    "apikey": "0ab215a8b1977939201640fa14c66bab"
}

### Top250 movie request /api/v1/top250movie
### 豆瓣电影Top250
post https://api.douban.com/v2/movie/top250 
Content-Type:application/json
 
{
    "start": 0,
    "count": 2,
    "city": "郑州",
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### new movie request /api/v1/newmovie  

### 最新上映影视 
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/movie/new_movies
Content-Type:application/json
 
{
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 北美票房榜
post https://api.douban.com/v2/movie/us_box
Content-Type:application/json
 
{
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}


### search movie request /api/v1/searchmovie
### 搜索电影
post https://api.douban.com/v2/movie/search
Content-Type:application/json
 
{
    "q": "肖申克的救赎",
    "start": 0,
    "count": 1,
    "apikey": "0ab215a8b1977939201640fa14c66bab"
}

### movie detail request /api/v1/moviedetail
### 电影详情
post https://api.douban.com/v2/movie/subject/1292052
Content-Type:application/json
 
{
    "apikey": "0ab215a8b1977939201640fa14c66bab"
}   

### movie comments request /api/v1/moviecomments
### 电影评论 短评 "msg": "need_permission", "code": 1000,
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/movie/subject/1292052/comments
Content-Type:application/json
 
{
    "start": 0,
    "count": 2,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### weekly movie request /api/v1/weeklymovie    
### 电影本周口碑榜 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/movie/weekly
Content-Type:application/json
 
{
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 电影条目剧照
post https://api.douban.com/v2/movie/subject/1292052/photos
Content-Type:application/json
 
{
    "start": 0,
    "count": 5,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### celebrity movie request /api/v1/celebritymovie
### 影人剧照 ----不能用
post https://api.douban.com/v2/movie/celebrity/1044707/photos
Content-Type:application/json
 
{
    "start": 0,
    "count": 1,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 电影 影评
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/movie/subject/1292052/reviews
Content-Type:application/json
 
{
    "start": 0,
    "count": 1,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 豆瓣音乐
### 不能用 0df993c66c0c636e29ecbb5344252a4a "msg": "apikey is required","code": 131,
post https://api.douban.com/v2/music/search
Content-Type:application/json
 
{
    "q": "周杰伦",
    "start": 0,
    "count": 1,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

###GET  https://api.douban.com/v2/music/:id
### 豆瓣音乐详情
### 不能用 0df993c66c0c636e29ecbb5344252a4a  "msg": "invalid_credencial2","code": 109,
get https://api.douban.com/v2/music/104727?apikey=0df993c66c0c636e29ecbb5344252a4a
Content-Type:application/json
 
{
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 豆瓣图书详情
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/book/2129650
Content-Type:application/json
 
{
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 豆瓣图书 评论
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/book/2129650/comments
Content-Type:application/json
 
{   
    "start": 0, 
    "count": 1,                     
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 豆瓣图书
### 0df993c66c0c636e29ecbb5344252a4a 能用
post https://api.douban.com/v2/book/search
Content-Type:application/json
 
{
    "q": "西游记",
    "start": 0,
    "count": 1,
    "apikey": "0df993c66c0c636e29ecbb5344252a4a"
}

### 豆瓣图书 热门
### 不可用 "msg": "invalid_credencial2","code": 109,
get https://api.douban.com/v2/book/top250?apikey=0b2bdeda43b5688921839c8ecb20399b




### 知乎热报
### 不能用 0df993c66c0c636e29ecbb5344252a4a  "msg": "invalid_credencial2","code": 109,      
get https://news-at.zhihu.com/api/4/news/latest


